# Generated by Django 2.2.2 on 2019-06-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('tipo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Tipo da receita')),
            ],
        ),
        migrations.CreateModel(
            name='receita',
            fields=[
                ('titulo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nome da receita')),
                ('ingrediente', models.TextField(verbose_name='Ingredientes:')),
                ('preparo', models.TextField(verbose_name='Modo de preparo:')),
                ('imagem', models.ImageField(null=True, upload_to='imagem', verbose_name='Imagem')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo')),
            ],
        ),
    ]
