# Generated by Django 2.2.2 on 2019-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Nome da receita'),
        ),
    ]
